# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c363a4e7d338e0009120767e9fd19a245771ede243a6c9368c3066c853fbc655b8ab7f64ad8b61ca945fcbc85ecf115abcb859bbfc8f5a47769bd396bbbe58

test:
  secret_key_base: 01a587cab03435918e0b311b31c8d7803e030550efb54a2f14a2350f5192264846c2e67e6ef061d12d66a7c61d43a8dfaf2a9283dc433819de7ab5da67b6d5c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
